import React,{useEffect,useRef,useState} from 'react';
import {AbsoluteFill,Composition,Easing,Img,Sequence,cancelRender,continueRender,delayRender,interpolate,registerRoot,spring,staticFile,useCurrentFrame as useRawCurrentFrame} from 'remotion';
import {Audio} from '@remotion/media';
import cueData from './caption-cues.json';

// Keep authored scene time separate from delivery frames. For a longer edit,
// change TIMELINE_SCALE and DURATION together; every scene guard, motion cue
// and sound cue must use these helpers rather than raw Remotion frames.
const BASE_FPS=30,FPS=30,MOTION_FPS=30,TIMELINE_SCALE=1,DURATION=900,DESIGN_SCALE=4/3;
const useCurrentFrame=()=>useRawCurrentFrame()*BASE_FPS/FPS/TIMELINE_SCALE;
const deliveryFrame=(designFrame:number)=>Math.round(designFrame*FPS*TIMELINE_SCALE/BASE_FPS);

// LOCKED AESTHETIC CORE: ordinary production runs must not edit this block.
const C={ink:'#2b2924',muted:'#746956',blue:'#2869b7',orange:'#ed5a32',green:'#43866a',gold:'#d2a128',red:'#bd4b3d',navy:'#2d3b4c',paper:'#fffdf7',paperWarm:'#f7ecd8',paperBase:'#f3e4c4',line:'#514a40',white:'#fff'};
const TYPE={displayXL:58,displayL:50,displayML:45,displayM:43,displayS:36,displayXS:34,titleXL:32,titleL:30,titleM:28,titleS:27,titleXS:26,bodyL:21,bodyM:20,bodyS:19,labelL:18,labelM:17,labelS:16,microL:15,microS:13,subtitle:40};
const AESTHETIC={subtitleSafeWidth:1334,paperRadius:12,paperOutline:1.6,textureOpacity:.026,gridOpacity:.09,gradeWarmth:.055,gradeVignette:.06};

// EDITABLE CONTENT SURFACE: ordinary models may replace copy and topic-specific labels here.
const COPY={
  chapterTitles:['升级原则','独立工位','连续装配','验证交付'],
  chromeKicker:'MOTION LAB / WIDE SPACE',
  header:'NOTEBOOK VIDEO / VISUAL DIRECTOR',
  headerSub:'IMAGE · TYPE · DIAGRAM / 2K30',
  act1:{stableTitle:'BASE STABLE',stableSub:'基础系统已经稳定',checks:['字幕同步','独立图层','自动质检'],beforeTitle:'EFFECT STACK',afterTitle:'OBJECT SYSTEM',beforeSub:'特效多，不等于画面好',afterSub:'一个物体，一个任务',chips:['ZOOM','GLOW','SPIN','PARTICLE','BLUR','SHAKE'],conclusionLeft:'视觉上限',conclusionRight:'特效数量'},
  act2:{workshops:[{kind:'script',label:'SCRIPT',title:'脚本结构'},{kind:'voice',label:'VOICE',title:'中文配音'},{kind:'caption',label:'CAPTION',title:'词级字幕'},{kind:'visual',label:'VISUAL',title:'图文导演'}],semanticCaption:'语义字幕同步',zoneLabel:'INDEPENDENT ZONE',footer:'FOUR WORKSHOPS / ONE SHARED CLOCK / COMPLETE OWNERSHIP'},
  act3:{states:[['BRIEF','任务卡'],['SCRIPTED','脚本完成'],['TIMED','时间锁定'],['READY','准备装配']],stations:[['BRIEF','接收'],['SCRIPT','结构'],['TIMING','同步'],['LAYER','分层']],modules:['SCRIPT','VOICE','CAPTION','VISUAL'],proof:'真实插槽 · 前后遮挡 · 磁吸锁定',assemblyTitle:'ASSEMBLY CORE',engineLabel:'ENGINE',lockLabel:'LAYER LOCK',footer:'ONE TASK CARD / SHARED TRACK / PHYSICAL OCCLUSION'},
  act4:{engine:'DELIVERY ENGINE',engineSub:'验证后，才允许交付',checks:['字幕宽度','音画同步','层级遮挡','黑帧检测'],outputs:[['MP4','H.264 / AAC 成片','play'],['PROJECT','完整 Remotion 工程','project'],['QA REPORT','自动质检结果','report']],finalLeft:'画面更复杂',finalRight:'故事依然清楚',footer:'H.264 / AAC / SOURCE PACKAGE / AUTOMATED QA'},
} as const;

const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const msFrame=(ms:number)=>Math.round(ms*FPS/1000);
const captions=((cueData as any).cues as any[]).map(c=>({...c,startFrame:msFrame(c.start_ms),endFrame:msFrame(c.speech_end_ms),words:c.words.map((w:any)=>({...w,startFrame:msFrame(w.start),endFrame:msFrame(w.end)}))}));
const q=(f:number)=>{const step=BASE_FPS/MOTION_FPS;return Math.floor(f/step)*step};
const ease=(f:number,a:number,b:number,from=0,to=1)=>interpolate(f,[a,b],[from,to],{...clamp,easing:Easing.inOut(Easing.cubic)});
const pop=(f:number,start:number,stiffness=120)=>spring({frame:f-start,fps:BASE_FPS,config:{damping:15,stiffness,mass:.76}});
const paperShadow=(lift:number)=>`${4+14*lift}px ${6+20*lift}px ${1+20*lift}px rgba(61,47,33,${.27-.13*lift}),0 ${12+30*lift}px ${22+34*lift}px rgba(49,35,22,${.105+.025*lift}),inset 0 1px 0 rgba(255,255,255,.72)`;

const preloadAudio=(src:string)=>new Promise<void>((resolve,reject)=>{const audio=new window.Audio(staticFile(src));audio.oncanplaythrough=()=>resolve();audio.onerror=()=>reject(new Error(`Required audio failed to load: ${src}`));audio.load()});
const preloadImage=(src:string)=>new Promise<void>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve();image.onerror=()=>reject(new Error(`Required image failed to load: ${src}`));image.src=staticFile(src)});
const AssetGate=()=>{const [handle]=useState(()=>delayRender('waiting for fonts, audio and image assets',{timeoutInMilliseconds:60000}));useEffect(()=>{let live=true;Promise.all([document.fonts.load('400 40px SourceHan'),document.fonts.load('700 40px SourceHan'),document.fonts.load('400 40px Smiley'),document.fonts.ready,...['narration.mp3','sfx/paper-rustle.wav','sfx/paper-tap.wav','sfx/data-whoosh.wav','sfx/chime.wav'].map(preloadAudio),...['illustrations/visual-director.png'].map(preloadImage)]).then(()=>{if(live)continueRender(handle)}).catch(error=>{if(live)cancelRender(error)});return()=>{live=false}},[handle]);return null};


// Non-visual QA gate: measure every full cue with the real loaded font.
// getBoundingClientRect() includes the 4/3 parent scale, so convert back to design pixels.
const CaptionFitGate=()=>{const ref=useRef<HTMLDivElement>(null),[done,setDone]=useState(false),[handle]=useState(()=>delayRender('measuring subtitle width',{timeoutInMilliseconds:60000}));useEffect(()=>{let live=true;Promise.all([document.fonts.load('400 40px SourceHan'),document.fonts.ready]).then(()=>requestAnimationFrame(()=>{if(!live)return;if(!ref.current){cancelRender(new Error('Subtitle measurement node is unavailable'));return}const rows=[...ref.current.querySelectorAll<HTMLElement>('[data-caption-fit]')];const overflow=rows.map((row,index)=>({index,width:row.getBoundingClientRect().width/DESIGN_SCALE,text:row.textContent||''})).filter(row=>row.width>AESTHETIC.subtitleSafeWidth+.5);if(overflow.length){cancelRender(new Error(`Subtitle overflow: ${overflow.map(x=>`#${x.index+1} ${Math.ceil(x.width)}px ${x.text}`).join(' | ')}`));return}setDone(true);continueRender(handle)})).catch(error=>{if(live)cancelRender(error)});return()=>{live=false}},[handle]);if(done)return null;return <div ref={ref} style={{position:'absolute',left:-10000,top:-10000,visibility:'hidden',fontFamily:'SourceHan,sans-serif',fontSize:40,fontWeight:400,whiteSpace:'nowrap'}}>{captions.map((cue:any,index:number)=><span key={index} data-caption-fit style={{display:'block',width:'max-content'}}>{String(cue.text).replace(/[，。！？；：、,.!?;:\s]+$/g,'')}</span>)}</div>};

const Fonts=()=> <style>{`
@font-face{font-family:SourceHan;src:url(${staticFile('SourceHanSansCN-Regular.otf')}) format('opentype');font-weight:400}
@font-face{font-family:SourceHan;src:url(${staticFile('SourceHanSansCN-Bold.otf')}) format('opentype');font-weight:700}
@font-face{font-family:Smiley;src:url(${staticFile('SmileySans-Oblique.otf')}) format('opentype')}
*{box-sizing:border-box}html,body{margin:0;background:${C.paperBase}}body{-webkit-font-smoothing:antialiased;text-rendering:geometricPrecision}
`}</style>;

const Background=()=> <>
  <AbsoluteFill style={{background:'radial-gradient(circle at 18% 10%,#fff9e7 0,#eeddbb 44%,#c89f6b 82%,#a57a4f 100%)'}}/>
  <div style={{position:'absolute',left:42,top:28,right:42,bottom:28,background:C.paperBase,border:'1.7px solid rgba(73,60,43,.40)',boxShadow:'22px 27px 0 rgba(75,57,38,.25),0 56px 104px rgba(42,25,12,.23),inset 0 1px 0 rgba(255,255,255,.42)'}}/>
  <div style={{position:'absolute',left:72,top:58,right:72,bottom:60,border:'1px solid rgba(90,72,48,.22)',backgroundImage:`repeating-linear-gradient(0deg,transparent 0 53px,rgba(94,74,50,${AESTHETIC.gridOpacity}) 54px),repeating-linear-gradient(90deg,transparent 0 53px,rgba(94,74,50,${AESTHETIC.gridOpacity}) 54px),radial-gradient(circle at 22% 8%,rgba(255,255,255,.28),transparent 42%)`}}/>
  <AbsoluteFill style={{opacity:AESTHETIC.textureOpacity,mixBlendMode:'multiply',backgroundImage:'radial-gradient(#3d2e1f 0.58px,transparent .75px)',backgroundSize:'7px 7px'}}/>
</>;

const Paper:React.FC<{children:React.ReactNode,style?:React.CSSProperties,lift?:number}>=({children,style,lift=0})=><div style={{position:'absolute',backgroundColor:C.paper,backgroundImage:'radial-gradient(circle at 18% 9%,rgba(255,255,255,.78),transparent 34%),repeating-linear-gradient(0deg,rgba(89,67,42,.015) 0 1px,transparent 1px 4px),linear-gradient(155deg,#fffef9,#f7ead3)',border:`${AESTHETIC.paperOutline}px solid ${C.line}`,borderRadius:AESTHETIC.paperRadius,color:C.ink,boxShadow:paperShadow(lift),...style}}>{children}</div>;

type IconKind='check'|'play'|'project'|'report';
const LineIcon:React.FC<{kind:IconKind,size?:number,color?:string,strokeWidth?:number}>=({kind,size=28,color='currentColor',strokeWidth=2.2})=>{const common={fill:'none',stroke:color,strokeWidth,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};return <svg width={size} height={size} viewBox="0 0 32 32" aria-hidden="true">{kind==='check'&&<path {...common} d="M7 16.5l5.6 5.5L25 9.8"/>}{kind==='play'&&<><rect {...common} x="5" y="6" width="22" height="20" rx="3"/><path {...common} d="M13 11.5l8 4.5-8 4.5z"/></>}{kind==='project'&&<><rect {...common} x="6" y="7" width="20" height="18" rx="2.5"/><path {...common} d="M10 12h12M10 16h8M10 20h6"/></>}{kind==='report'&&<><path {...common} d="M9 5h10l5 5v17H9z"/><path {...common} d="M19 5v6h5M13 16h7M13 20h7"/></>}</svg>};
const CheckBadge:React.FC<{size?:number}>=({size=30})=><span style={{width:size,height:size,borderRadius:999,background:C.green,color:C.white,display:'inline-grid',placeItems:'center',flex:'0 0 auto'}}><LineIcon kind="check" size={size*.62} color={C.white} strokeWidth={2.7}/></span>;

const cleanTail=(s:string)=>s.replace(/[，。！？；：、,.!?;:\s]+$/g,'');
const Subtitle=()=>{const f=useRawCurrentFrame(),lead=Math.round(FPS*.06),hold=Math.round(FPS*.267);let cue=captions.find((c:any)=>f>=c.startFrame-lead&&f<=c.endFrame+hold);if(!cue)cue=[...captions].reverse().find((c:any)=>c.startFrame<=f);const full=cue?cleanTail(cue.text):'';const shown=cue?cleanTail(cue.words.filter((w:any)=>w.startFrame<=f+lead).map((w:any)=>w.part).join('')):'';return <div style={{position:'absolute',left:188,right:188,bottom:34,height:112,zIndex:200,background:C.paper,clipPath:'polygon(0 8%,3% 3%,6% 7%,9% 2%,12% 6%,15% 1%,18% 5%,21% 2%,24% 7%,27% 2%,30% 5%,33% 1%,36% 6%,39% 2%,42% 7%,45% 1%,48% 5%,51% 2%,54% 7%,57% 2%,60% 5%,63% 1%,66% 6%,69% 2%,72% 7%,75% 2%,78% 5%,81% 1%,84% 6%,87% 2%,90% 7%,93% 2%,96% 5%,100% 3%,100% 95%,97% 99%,94% 94%,91% 100%,88% 95%,85% 99%,82% 94%,79% 99%,76% 95%,73% 100%,70% 94%,67% 99%,64% 95%,61% 100%,58% 94%,55% 99%,52% 95%,49% 100%,46% 94%,43% 99%,40% 95%,37% 100%,34% 94%,31% 99%,28% 95%,25% 100%,22% 94%,19% 99%,16% 95%,13% 100%,10% 94%,7% 99%,4% 95%,0 98%)',filter:'drop-shadow(7px 8px 0 rgba(92,75,55,.22)) drop-shadow(0 14px 20px rgba(48,35,22,.14))',display:'grid',placeItems:'center',padding:'0 105px'}}>
  <div style={{position:'absolute',left:28,top:28,bottom:28,width:10,borderRadius:4,background:C.orange}}/>
  <div style={{width:AESTHETIC.subtitleSafeWidth,display:'grid',placeItems:'center',fontSize:TYPE.subtitle,lineHeight:1.18,letterSpacing:.1,whiteSpace:'nowrap'}}><span style={{position:'relative'}}><span style={{visibility:'hidden'}}>{full}</span><span style={{position:'absolute',left:0,top:0}}>{shown}</span></span></div>
  <div style={{position:'absolute',right:24,top:34,width:44,height:44,borderRadius:99,border:`3.5px solid ${C.blue}`,display:'grid',placeItems:'center'}}><div style={{width:15,height:15,borderRadius:99,background:C.blue,boxShadow:`0 0 15px rgba(40,105,183,.55)`}}/></div>
</div>};

const Chrome=()=>{const f=q(useCurrentFrame()),stage=f<195?0:f<330?1:f<650?2:3,starts=[0,195,330,650],local=f-starts[stage],p=pop(local,-8),titles=COPY.chapterTitles;return <>
  <Paper style={{left:92,top:74,width:350,height:82,zIndex:150,display:'flex',opacity:p,transform:`translateY(${14*(1-p)}px) scale(${.96+.04*p})`}}><div style={{width:72,background:C.orange,color:C.white,display:'grid',placeItems:'center',fontFamily:'Smiley',fontSize:31}}>{String(stage+1).padStart(2,'0')}</div><div style={{padding:'10px 16px'}}><div style={{fontSize:TYPE.microS,color:C.blue,fontWeight:700,letterSpacing:2}}>{COPY.chromeKicker}</div><div style={{fontSize:TYPE.titleS,fontWeight:700,marginTop:3}}>{titles[stage]}</div></div></Paper>
  <div style={{position:'absolute',right:88,top:70,zIndex:140,textAlign:'right'}}><div style={{fontSize:TYPE.labelM,fontWeight:700,letterSpacing:4,color:C.blue}}>{COPY.header}</div><div style={{fontSize:TYPE.microL,marginTop:7,color:C.muted}}>{COPY.headerSub}</div></div>
</>};

const stageFade=(f:number,start:number,end:number)=>ease(f,start,start+15)*ease(f,end-15,end,1,0);

const FinalActOne=()=>{const f=q(useCurrentFrame()),opacity=stageFade(f,-5,195),reorder=ease(f,82,150),chips=[...COPY.act1.chips];return <div style={{position:'absolute',inset:0,opacity}}>
  <Paper style={{left:175,top:245,width:650,height:430,zIndex:70,padding:'42px 46px',borderColor:C.green,transform:`translateY(${28*(1-pop(f,5,135))}px) scale(${.95+.05*pop(f,5,135)})`}}><div style={{fontFamily:'Smiley',fontSize:TYPE.displayXL,color:C.green}}>{COPY.act1.stableTitle}</div><div style={{fontSize:TYPE.titleL,fontWeight:700,marginTop:14}}>{COPY.act1.stableSub}</div><div style={{position:'absolute',left:48,right:48,bottom:55,height:170}}>{COPY.act1.checks.map((x,i)=><div key={x} style={{position:'absolute',left:0,right:0,top:i*56,height:42,background:'#eadcc1',border:'2px solid #6b5f50',boxShadow:'6px 7px 0 rgba(64,49,35,.18)',transform:`translateX(${26*(1-pop(f,28+i*20,145))}px)`,opacity:pop(f,28+i*20,145)}}><div style={{width:`${58+i*14}%`,height:'100%',background:[C.blue,C.orange,C.green][i],opacity:.82}}/><span style={{position:'absolute',left:18,top:7,color:C.white,fontSize:TYPE.bodyM,fontWeight:700}}>{x}</span><span style={{position:'absolute',right:14,top:5}}><CheckBadge size={30}/></span></div>)}</div></Paper>
  <Paper style={{left:1095,top:245,width:650,height:430,zIndex:70,padding:'42px 46px',borderColor:reorder>.72?C.green:C.red,transform:`translateY(${28*(1-pop(f,18,135))}px) scale(${.95+.05*pop(f,18,135)})`}}><div style={{fontFamily:'Smiley',fontSize:TYPE.displayXL,color:reorder>.72?C.green:C.red}}>{reorder>.72?COPY.act1.afterTitle:COPY.act1.beforeTitle}</div><div style={{fontSize:TYPE.titleM,fontWeight:700,marginTop:14}}>{reorder>.72?COPY.act1.afterSub:COPY.act1.beforeSub}</div><div style={{position:'absolute',left:45,right:45,bottom:45,height:190}}>{chips.map((x,i)=>{const gx=(i%3)*174,gy=Math.floor(i/3)*90,stackX=185+(i%3)*12,stackY=55+Math.floor(i/3)*10;return <div key={x} style={{position:'absolute',left:stackX,top:stackY,width:145,height:62,display:'grid',placeItems:'center',background:C.paper,border:`3px solid ${[C.orange,C.blue,C.green,C.gold,C.red,C.navy][i]}`,boxShadow:'7px 9px 0 rgba(63,49,35,.22)',fontFamily:'Smiley',fontSize:TYPE.bodyM,transform:`translate3d(${(gx-stackX)*reorder}px,${(gy-stackY)*reorder}px,0) rotate(${(i%2?5:-5)*(1-reorder)}deg) scale(${.88+.12*pop(f,48+i*9,150)})`}}>{x}</div>})}</div></Paper>
  <Paper style={{left:610,top:735,width:700,height:92,zIndex:85,display:'grid',placeItems:'center',borderColor:C.orange,transform:`scale(${pop(f,118,160)})`}}><div style={{fontSize:TYPE.titleXL,fontWeight:700}}>{COPY.act1.conclusionLeft} <span style={{color:C.red,margin:'0 24px'}}>≠</span> {COPY.act1.conclusionRight}</div></Paper>
</div>};

type WorkshopKind='script'|'voice'|'caption'|'visual';
const Workshop:React.FC<{x:number;kind:WorkshopKind;label:string;title:string;color:string;start:number}>=({x,kind,label,title,color,start})=>{const f=q(useCurrentFrame()),l=f-195,p=pop(l,start,145),active=ease(l,start+20,start+55);return <Paper lift={active*.18} style={{left:x,top:250,width:370,height:470,zIndex:75,padding:'30px 30px',borderColor:color,transform:`translateY(${30*(1-p)}px) scale(${.94+.06*p})`}}><div style={{fontFamily:'Smiley',fontSize:TYPE.displayM,color}}>{label}</div><div style={{fontSize:TYPE.titleS,fontWeight:700,marginTop:8}}>{title}</div><div style={{position:'absolute',left:28,right:28,top:155,bottom:72,border:'2px dashed rgba(76,65,51,.36)',background:'rgba(245,232,202,.48)'}}>
  {kind==='script'&&[0,1,2,3].map(i=><div key={i} style={{position:'absolute',left:28,top:28+i*45,height:18,width:`${ease(l,start+12+i*10,start+36+i*10)*(245-i*25)}px`,background:i===0?color:C.muted,borderRadius:5}}/>)}
  {kind==='voice'&&<div style={{position:'absolute',left:28,right:28,top:82,height:90,display:'flex',alignItems:'center',gap:7}}>{Array.from({length:24},(_,i)=><div key={i} style={{width:7,height:18+62*Math.abs(Math.sin(i*.62+l*.13))*active,background:i%4===0?C.orange:color,borderRadius:4}}/>)}</div>}
  {kind==='caption'&&<><div style={{position:'absolute',left:24,right:24,top:82,height:72,background:C.paper,clipPath:'polygon(0 10%,8% 3%,16% 9%,24% 2%,32% 8%,40% 3%,48% 9%,56% 2%,64% 8%,72% 3%,80% 9%,88% 2%,100% 8%,100% 94%,90% 100%,80% 93%,70% 100%,60% 94%,50% 100%,40% 93%,30% 100%,20% 94%,10% 100%,0 93%)',display:'grid',placeItems:'center',fontSize:TYPE.bodyM}}>{COPY.act2.semanticCaption}</div><div style={{position:'absolute',left:32,top:180,width:240,height:7,background:'#c9b99e'}}><div style={{height:'100%',width:`${active*100}%`,background:color}}/></div></>}
  {kind==='visual'&&<><Img src={staticFile('illustrations/visual-director.png')} style={{position:'absolute',inset:0,width:'100%',height:'100%',objectFit:'cover',transform:`scale(${1.07-.035*active})`,transformOrigin:'52% 48%'}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(180deg,transparent 42%,rgba(43,41,36,.72) 100%)'}}/><div style={{position:'absolute',left:18,top:18,width:112,height:82,border:`5px solid ${C.orange}`,opacity:ease(l,start+18,start+34)*ease(l,start+67,start+78,1,0)}}/><div style={{position:'absolute',right:15,top:20,width:106,height:88,border:`5px solid ${C.green}`,opacity:ease(l,start+38,start+54)*ease(l,start+76,start+88,1,0)}}/><div style={{position:'absolute',left:18,bottom:18,background:C.paper,padding:'7px 11px',fontSize:TYPE.microS,fontWeight:700,color:C.orange,boxShadow:'4px 5px 0 rgba(55,42,29,.22)',opacity:ease(l,start+28,start+43)}}>IMAGE + TYPE</div><div style={{position:'absolute',right:16,bottom:18,color:C.white,fontSize:TYPE.microS,fontWeight:700,letterSpacing:1,opacity:ease(l,start+48,start+62)}}>看见 → 标注 → 结论</div></>}
 </div><div style={{position:'absolute',left:30,right:30,bottom:24,height:34,display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:TYPE.labelM,color:C.muted}}><span>{COPY.act2.zoneLabel}</span><span style={{width:30,height:30,borderRadius:99,background:active>.8?C.green:'#d3c4aa',display:'grid',placeItems:'center'}}>{active>.8?<LineIcon kind="check" size={19} color={C.white} strokeWidth={2.7}/>:<span style={{width:7,height:7,borderRadius:99,background:C.white}}/>}</span></div></Paper>};

const FinalActTwo=()=>{const f=q(useCurrentFrame()),opacity=stageFade(f,180,330);return <div style={{position:'absolute',inset:0,opacity}}>
  {COPY.act2.workshops.map((item,i)=><Workshop key={item.kind} x={100+i*450} kind={item.kind} label={item.label} title={item.title} color={[C.orange,C.blue,C.green,C.gold][i]} start={3+i*13}/>) }
  <div style={{position:'absolute',left:155,top:830,fontSize:TYPE.microL,color:C.muted,letterSpacing:3}}>{COPY.act2.footer}</div>
</div>};

const TaskStation:React.FC<{x:number;title:string;sub:string;color:string;index:number;local:number}>=({x,title,sub,color,index,local})=>{const p=pop(local,5+index*12,145),hit=ease(local,34+index*34,48+index*34)*ease(local,70+index*34,86+index*34,1,0),exit=ease(local,176,202,1,0);return <Paper lift={hit*.28} style={{left:x,top:235,width:255,height:150,zIndex:78,padding:'24px 24px',borderColor:color,opacity:exit,transform:`translateY(${24*(1-p)-11*hit}px) scale(${.94+.06*p})`}}><div style={{fontFamily:'Smiley',fontSize:TYPE.displayXS,color}}>{title}</div><div style={{fontSize:TYPE.bodyL,fontWeight:700,marginTop:10}}>{sub}</div><div style={{position:'absolute',right:22,top:22,width:22,height:22,borderRadius:99,background:hit?color:'#d5c7ad',boxShadow:hit?`0 0 22px ${color}`:'none'}}/><div style={{position:'absolute',left:22,right:22,bottom:20,height:8,background:'#d6c6aa'}}><div style={{height:'100%',width:`${hit*100}%`,background:color}}/></div></Paper>};

const AssemblyMachine:React.FC<{local:number}>=({local})=>{const l=q(local),p=pop(l,92,140),unfold=ease(l,118,205),lock=pop(l,238,165),colors=[C.orange,C.blue,C.green,C.gold];return <div style={{position:'absolute',left:1335,top:210,width:500,height:550,zIndex:90,transform:`scale(${p})`}}>
  <Paper style={{left:38,top:35,width:430,height:440,zIndex:72,borderColor:C.navy,background:'linear-gradient(145deg,#e8d6b4,#d9c39b)'}}><div style={{position:'absolute',left:24,right:24,top:22,height:52,fontFamily:'Smiley',fontSize:TYPE.titleXL,color:C.navy}}>{COPY.act3.assemblyTitle}</div><div style={{position:'absolute',left:115,top:85,width:210,height:210,borderRadius:40,background:'linear-gradient(145deg,#314258,#202a36)',border:'4px solid #17202a',boxShadow:'11px 14px 0 rgba(56,42,29,.28)',display:'grid',placeItems:'center',color:C.white,transform:`scale(${.86+.14*lock})`}}><div style={{textAlign:'center'}}><div style={{fontFamily:'Smiley',fontSize:TYPE.displayML,color:'#7cc5ff'}}>{COPY.act3.engineLabel}</div><div style={{fontSize:TYPE.labelS,letterSpacing:3,marginTop:8}}>{COPY.act3.lockLabel}</div></div></div>{colors.map((c,i)=><div key={c} style={{position:'absolute',left:70+(i%2)*220,top:330+Math.floor(i/2)*55,width:160,height:35,border:`2px solid ${c}`,background:C.paper}}><div style={{height:'100%',width:`${ease(l,155+i*24,180+i*24)*100}%`,background:c,opacity:.82}}/></div>)}</Paper>
  {[{x:118,y:116,tx:0,ty:-82,r:0,c:C.orange},{x:118,y:116,tx:90,ty:0,r:90,c:C.green},{x:118,y:116,tx:0,ty:90,r:180,c:C.gold},{x:118,y:116,tx:-90,ty:0,r:-90,c:C.blue}].map((a,i)=><Paper key={i} lift={Math.sin(Math.PI*unfold)*.35} style={{left:78+a.x+a.tx*unfold,top:18+a.y+a.ty*unfold,width:120,height:82,zIndex:68,borderColor:a.c,transform:`rotate(${a.r*unfold}deg) rotateX(${72*(1-unfold)}deg) scale(${.7+.3*unfold})`}}><div style={{position:'absolute',left:22,right:22,top:37,height:6,background:a.c}}/></Paper>)}
  <div style={{position:'absolute',left:8,top:245,width:128,height:105,zIndex:74,background:C.navy,border:'4px solid #17202a',borderRadius:'12px 0 0 12px'}}/>
  <Paper style={{left:4,top:305,width:155,height:92,zIndex:118,borderColor:C.navy,background:'linear-gradient(#314258,#202a36)'}}><div style={{position:'absolute',left:20,right:20,top:22,height:7,background:'#7cc5ff'}}/><div style={{position:'absolute',left:20,right:20,top:46,height:7,background:'#7cc5ff'}}/></Paper>
  <div style={{position:'absolute',left:173,top:120,width:165,height:165,zIndex:110,borderRadius:'50%',border:`5px solid ${C.green}`,opacity:ease(l,232,250)*ease(l,278,294,1,0),transform:`scale(${.55+.75*ease(l,232,270)})`,boxShadow:`0 0 28px ${C.green}`}}/>
</div>};

const FinalActThree=()=>{const f=q(useCurrentFrame()),l=f-330,opacity=stageFade(f,315,650),stationExit=ease(l,176,202,1,0),states=COPY.act3.states.map((item,i)=>[item[0],item[1],[C.orange,C.blue,C.green,C.gold][i]] as const),t=ease(l,28,154),state=Math.min(3,Math.floor(t*4)),x=105+1260*t,y=505-72*Math.sin(Math.PI*t),taskFade=ease(l,154,178,1,0);const modules=COPY.act3.modules.map((name,i)=>[name,[C.orange,C.blue,C.green,C.gold][i],120+i*310,255] as const);return <div style={{position:'absolute',inset:0,opacity}}>
  <svg width="1920" height="1080" style={{position:'absolute',inset:0,zIndex:55}}><path d="M120 550 C430 470 690 630 960 545 S1260 490 1450 535" fill="none" stroke={C.muted} strokeWidth="11" strokeLinecap="butt" opacity={.38*stationExit}/><path d="M120 550 C430 470 690 630 960 545 S1260 490 1450 535" fill="none" stroke={states[state][2]} strokeWidth="6" strokeLinecap="butt" strokeDasharray="24 19" strokeDashoffset={-l*4} opacity={stationExit}/></svg>
  {COPY.act3.stations.map((item,i)=>[item[0],item[1],[C.orange,C.blue,C.green,C.gold][i]] as const).map((s,i)=><TaskStation key={s[0]} x={95+i*310} title={s[0]} sub={s[1]} color={s[2]} index={i} local={l}/>) }
  <Paper lift={Math.sin(Math.PI*t)} style={{left:105,top:505,width:225,height:105,zIndex:t>.91?73:96,padding:'19px 22px',borderColor:states[state][2],opacity:taskFade,transform:`translate3d(${x-105}px,${y-505}px,0) rotate(${7*Math.sin(t*Math.PI*2)}deg) scale(${1-.18*t})`}}><div style={{fontFamily:'Smiley',fontSize:31,color:states[state][2]}}>{states[state][0]}</div><div style={{fontSize:TYPE.labelL,fontWeight:700,marginTop:7}}>{states[state][1]}</div><div style={{position:'absolute',right:16,top:16,width:17,height:17,borderRadius:99,background:states[state][2],boxShadow:`0 0 16px ${states[state][2]}`}}/></Paper>
  <AssemblyMachine local={l}/>
  {modules.map((m,i)=>{const start=165+i*25,u=ease(l,start,start+58),fade=ease(l,start+48,start+62,1,0),targetX=1360,targetY=505;return <Paper key={m[0]} lift={Math.sin(Math.PI*u)} style={{left:m[2],top:m[3],width:190,height:72,zIndex:u>.85?73:94,display:'grid',placeItems:'center',borderColor:m[1],opacity:fade,transform:`translate3d(${(targetX-m[2])*u}px,${(targetY-m[3])*u}px,0) scale(${1-.45*u}) rotate(${(i%2?5:-5)*(1-u)}deg)`}}><div style={{fontFamily:'Smiley',fontSize:25,color:m[1]}}>{m[0]}</div></Paper>})}
  <Paper style={{left:470,top:720,width:720,height:88,zIndex:82,display:'grid',placeItems:'center',borderColor:C.green,opacity:ease(l,225,250),transform:`translateY(${18*(1-pop(l,225,155))}px)`}}><div style={{fontSize:TYPE.titleS,fontWeight:700}}>{COPY.act3.proof}</div></Paper>
  <div style={{position:'absolute',left:155,top:850,fontSize:TYPE.microL,color:C.muted,letterSpacing:3}}>{COPY.act3.footer}</div>
</div>};

const OutputArtifact:React.FC<{x:number;title:string;sub:string;color:string;start:number;icon:IconKind;local:number}>=({x,title,sub,color,start,icon,local})=>{const u=ease(local,start,start+72),p=pop(local,start+55,155),lift=Math.sin(Math.PI*u),visible=ease(local,start,start+10);return <Paper lift={lift} style={{left:580,top:500,width:310,height:225,zIndex:88,padding:'28px 28px',borderColor:color,opacity:visible,transform:`translate3d(${(x-580)*u}px,${-180*Math.sin(Math.PI*u)}px,0) rotate(${7*Math.sin(u*Math.PI*2)}deg) scale(${.72+.28*p})`}}><div style={{height:50,display:'flex',alignItems:'center',color}}><LineIcon kind={icon} size={48} color={color} strokeWidth={2}/></div><div style={{fontFamily:'Smiley',fontSize:TYPE.displayS,color,marginTop:8}}>{title}</div><div style={{fontSize:TYPE.bodyM,fontWeight:700,marginTop:9}}>{sub}</div><div style={{position:'absolute',right:22,top:22,transform:`scale(${pop(local,start+78,170)})`}}><CheckBadge size={34}/></div></Paper>};

const FinalActFour=()=>{const f=q(useCurrentFrame()),l=f-650,opacity=ease(f,635,650),scan=ease(l,122,190),final=ease(l,184,224);return <div style={{position:'absolute',inset:0,opacity}}>
  <Paper style={{left:120,top:245,width:520,height:455,zIndex:76,padding:'38px 42px',borderColor:C.navy,background:'linear-gradient(145deg,#e7d4b0,#d8bd91)',transform:`scale(${pop(l,0,140)})`}}><div style={{fontFamily:'Smiley',fontSize:TYPE.displayL,color:C.navy}}>{COPY.act4.engine}</div><div style={{fontSize:TYPE.titleXS,fontWeight:700,marginTop:10}}>{COPY.act4.engineSub}</div><div style={{position:'absolute',left:42,right:42,top:145,height:190,display:'grid',gridTemplateColumns:'1fr 1fr',gap:15}}>{COPY.act4.checks.map((x,i)=><div key={x} style={{background:C.paper,border:`2px solid ${[C.orange,C.blue,C.green,C.gold][i]}`,display:'flex',alignItems:'center',padding:'0 15px',fontSize:TYPE.bodyS,fontWeight:700,transform:`scale(${pop(l,18+i*15,150)})`}}><span style={{marginRight:12,display:'inline-flex'}}><CheckBadge size={30}/></span>{x}</div>)}</div><div style={{position:'absolute',left:42,right:42,bottom:40,height:18,background:'#bfae91',borderRadius:12,overflow:'hidden'}}><div style={{height:'100%',width:`${ease(l,24,132)*100}%`,background:`linear-gradient(90deg,${C.blue},${C.green},${C.gold})`}}/></div></Paper>
  <svg width="1920" height="1080" style={{position:'absolute',inset:0,zIndex:55}}>{[[750,C.blue],[1110,C.green],[1470,C.gold]].map((a,i)=><path key={i} d={`M600 500 C680 ${350+i*70} ${a[0]-80} ${380+i*35} ${a[0]} 430`} fill="none" stroke={a[1]} strokeWidth="6" strokeLinecap="butt" strokeDasharray="19 16" strokeDashoffset={-l*3} opacity={ease(l,18+i*25,36+i*25)*ease(l,130+i*15,155+i*15,1,0)}/>)}</svg>
  {COPY.act4.outputs.map((item,i)=><OutputArtifact key={item[0]} x={[720,1080,1440][i]} title={item[0]} sub={item[1]} color={[C.blue,C.green,C.gold][i]} start={28+i*30} icon={item[2]} local={l}/>) }
  <div style={{position:'absolute',left:675,top:225,width:13,height:500,zIndex:105,background:'linear-gradient(transparent,#ffefad,#42a776,#ffefad,transparent)',boxShadow:'0 0 34px #42a776',opacity:ease(l,118,132)*ease(l,188,202,1,0),transform:`translate3d(${1080*scan}px,0,0)`}}/>
  <Paper style={{left:650,top:730,width:1110,height:105,zIndex:112,display:'grid',placeItems:'center',borderColor:C.orange,opacity:final,transform:`translateY(${22*(1-final)}px) scale(${.96+.04*pop(l,182,160)})`}}><div style={{fontSize:TYPE.titleXL,fontWeight:700}}>{COPY.act4.finalLeft} <span style={{color:C.orange,margin:'0 25px'}}>·</span> {COPY.act4.finalRight} <span style={{marginLeft:25,display:'inline-flex',verticalAlign:'middle'}}><CheckBadge size={42}/></span></div></Paper>
  <div style={{position:'absolute',left:155,top:850,fontSize:TYPE.microL,color:C.muted,letterSpacing:3}}>{COPY.act4.footer}</div>
</div>};

const FinalDemo=()=>{const f=q(useCurrentFrame());return <>{f<195&&<FinalActOne/>}{f>=195&&f<330&&<FinalActTwo/>}{f>=330&&f<650&&<FinalActThree/>}{f>=650&&<FinalActFour/>}</>};

const Sound=()=> <>
  <Audio src={staticFile('narration.mp3')} volume={1}/>
  {[8,22,205,218,231,244,495,520,545,570].map(f=><Sequence key={`r${f}`} from={deliveryFrame(f)} layout="none"><Audio src={staticFile('sfx/paper-rustle.wav')} volume={.13}/></Sequence>)}
  {[358,392,426,460,678,708,738].map(f=><Sequence key={`w${f}`} from={deliveryFrame(f)} layout="none"><Audio src={staticFile('sfx/data-whoosh.wav')} volume={.12}/></Sequence>)}
  {[38,68,112,145,238,251,264,277,364,398,432,466,505,530,555,580,690,720,750,805].map(f=><Sequence key={`t${f}`} from={deliveryFrame(f)} layout="none"><Audio src={staticFile('sfx/paper-tap.wav')} volume={.15}/></Sequence>)}
  {[170,595,850].map(f=><Sequence key={`c${f}`} from={deliveryFrame(f)} layout="none"><Audio src={staticFile('sfx/chime.wav')} volume={.18}/></Sequence>)}
</>;

const Grade=()=> <AbsoluteFill style={{pointerEvents:'none',zIndex:190}}><AbsoluteFill style={{opacity:AESTHETIC.gradeWarmth,mixBlendMode:'soft-light',background:'radial-gradient(circle at 24% 8%,rgba(255,249,224,.9),transparent 48%),linear-gradient(180deg,rgba(255,244,216,.14),rgba(84,55,28,.08))'}}/><AbsoluteFill style={{boxShadow:`inset 0 0 150px rgba(66,42,22,${AESTHETIC.gradeVignette})`}}/></AbsoluteFill>;
const Film=()=> <AbsoluteFill style={{overflow:'hidden',background:C.paperBase}}><div style={{position:'absolute',left:0,top:0,width:1920,height:1080,transform:'scale(1.3333333333)',transformOrigin:'0 0',fontFamily:'SourceHan,sans-serif',color:C.ink,overflow:'hidden'}}><Fonts/><AssetGate/><CaptionFitGate/><Sound/><Background/><FinalDemo/><Chrome/><Grade/><Subtitle/></div></AbsoluteFill>;
const Root=()=> <Composition id="NotebookVideoFilm" component={Film} durationInFrames={DURATION} fps={FPS} width={2560} height={1440}/>;
registerRoot(Root);
